blank_issues_enabled: false
contact_links:
  - name: ❓ Questions and everything else
    url: https://github.com/scribe-org/Scribe-Android/discussions
    about: Join us in the Scribe-Android community Discussions!
