name: pr_ktlint
on:
    pull_request:
        branches:
            - main
        types: [opened, reopened, synchronize]

jobs:
    ktlint:
        runs-on: ubuntu-latest
        name: Run ktlint

        steps:
            - name: Clone repo
              uses: actions/checkout@master
              with:
                  fetch-depth: 1

            - name: GitHub Action for ktlint
              uses: ScaCap/action-ktlint@master
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review
